@startuml
class Jogador {
    - id : String
    - nome : String
    - gols : int
    + cadastrar() : void
}
class Jogo {
    - local : String
    - data : String
    - MaxJoagadores : int
    + cadastrar() : void
}
Jogador -- Jogo
@enduml